### PR TITLE
Update Expo example to Expo version 20

### LINKED ISSUE #9: Migrate expo example to v20

### PR DESCRIPTION
**Pull request by reggie3**
Expo example updated to Expo version 20 using the steps outlined in this blog post: [https://blog.expo.io/expo-sdk-v20-0-0-is-now-available-79f84232a9d1](https://blog.expo.io/expo-sdk-v20-0-0-is-now-available-79f84232a9d1)

Followed the steps outlined at [https://gist.github.com/MarcDiethelm/7303312](https://gist.github.com/MarcDiethelm/7303312) for contributing to the project.

Closes #9

### CODE REVIEW

**Comment by R1ZZU** [comment]
Checked this out, worked well without any modifications (except I had to remove expo app from simulator which is expected), great work 👍 🎉 

 However after `yarn` installs all packages, I have `yarn.lock` modified. Could you please remove `yarn.lock` and run `yarn` in order to update lockfile? and don't forget to push this changes, after that I will merge this right away 🚀

**Comment by R1ZZU** [comment]
You can also mention in PR description that it closes #9 Then issue #9 will be closed automatically after this PR will be merged. More info [here](https://help.github.com/articles/closing-issues-using-keywords/)

**Comment by reggie3** [comment]
Thanks. I'll update it and retry in a few hours.

**Comment by reggie3** [comment]
Okay, I removed the yarn.lock and ran yarn again.  I think I may have
messed up on the pull request by not including "Closes #9" in the my local
commit message; however, I tried to included in the commit comment on
Github.  Unfortunately, I did it after I pressed the pull request button.

**Comment by R1ZZU** [comment]
great, yarn.lock is now up to date. This "autoclose issue" stuff is not a mandatory step, just giving you more insight on github features. It's not a problem if you forgot to mention that your pr closes some issue at the stage of pr submission, as you can edit PR description later (actually not just you, but project owner as well).

Thanks for your contribution and accept my congratulations with your first opensource contribution! 🎉 👍

**Comment by reggie3** [comment]
Great!  Thanks again for walking me through it.

**Pull request merged**
